site_name: AEAT VERI*FACTU API Documentation
site_description: Complete technical documentation for AEAT VERI*FACTU SOAP webservice
site_author: Nigel Becholtz
site_url: https://NigelBecholtz.github.io/verifactu-docs

# Repository
repo_name: NigelBecholtz/verifactu-docs
repo_url: https://github.com/NigelBecholtz/verifactu-docs

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Quick Reference: quick-reference.md
  - Getting Started:
    - getting-started.md
    - Overview: README.md
    - Authentication: authentication.md
    - Endpoints: endpoints.md
    - Certificate Guide: certificate-guide.md
    - Certificate Visual Guide: certificate-visual-guide.md
  - API Operations:
    - Register Invoice: alta-register-invoice.md
    - Cancel Invoice: baja-cancel-invoice.md
    - Query Invoice: consulta-query-invoice.md
  - Technical Details:
    - Parameters & Fields: parameters-and-fields.md
    - XSD Schema Reference: xsd-schema-reference.md
    - Error Handling: error-handling.md
    - Node.js Implementation: node-implementation.md
    - Implementation Examples: implementation-examples.md
    - SLA & Performance: sla-performance.md
  - Compliance:
    - Legal Compliance: legal-compliance.md
  - Examples: examples.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NigelBecholtz
